name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno fmt --check

      # cat-dir-rs
      - run: cd cat-dir-rs && cargo fmt --check

      - run: cd cat-dir-rs && cargo build
      - run: cd cat-dir-rs && cargo test
      - run: cd cat-dir-rs && cargo doc

      # release: x86_64-unknown-linux-gnu
      - run: cd cat-dir-rs && cargo build --release
      - uses: actions/upload-artifact@v6
        with:
          name: cat-dir-x86_64-linux-gnu
          path: cat-dir-rs/target/release/cat-dir

      # TODO

      # use cat-dir bundle cat-dir
      - run: git clone --depth=1 --single-branch https://github.com/fm-elpac/cat-dir.git cat-dir-src
      - run: rm -rf cat-dir-src/.git
      - run: node npm/bin/cat-dir.js cat-dir-src cat-dir-src.cat-dir.txt

      - uses: actions/upload-artifact@v6
        with:
          name: cat-dir-src.cat-dir.txt
          path: cat-dir-src.cat-dir.txt
